/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/arregladoxd.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[0.1, 0.1, 0.02]}>
        <group position={[6.39, 14.49, 1.97]} rotation={[0.36, -1.57, 0]} scale={0.46}>
          <mesh geometry={nodes.Cone003.geometry} material={nodes.Cone003.material} />
          <mesh geometry={nodes.Cone003_1.geometry} material={nodes.Cone003_1.material} />
          <mesh geometry={nodes.Cone003_2.geometry} material={nodes.Cone003_2.material} />
        </group>
        <group position={[0.02, 14.49, 1.97]} rotation={[0.36, -1.57, 0]} scale={0.46}>
          <mesh geometry={nodes.Cone004.geometry} material={nodes.Cone004.material} />
          <mesh geometry={nodes.Cone004_1.geometry} material={nodes.Cone004_1.material} />
          <mesh geometry={nodes.Cone004_2.geometry} material={nodes.Cone004_2.material} />
        </group>
        <group position={[-6.28, 14.49, 1.97]} rotation={[0.36, -1.57, 0]} scale={0.46}>
          <mesh geometry={nodes.Cone005.geometry} material={nodes.Cone005.material} />
          <mesh geometry={nodes.Cone005_1.geometry} material={nodes.Cone005_1.material} />
          <mesh geometry={nodes.Cone005_2.geometry} material={nodes.Cone005_2.material} />
        </group>
        <group position={[0, 6.87, 0]} scale={[6.94, 6.94, 0.56]}>
          <mesh geometry={nodes.Cube002.geometry} material={materials['screen-A']} />
          <mesh geometry={nodes.Cube002_1.geometry} material={nodes.Cube002_1.material} />
        </group>
        <mesh geometry={nodes['billboard-wireframe'].geometry} material={nodes['billboard-wireframe'].material} position={[0, 6.87, 0]} scale={[6.94, 6.94, 0.56]} />
      </group>
      <directionalLight intensity={1} decay={2} position={[1.42, 7.15, 7.54]} />
    </group>
  )
}

useGLTF.preload('/arregladoxd.gltf')
