/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Brainz.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 3.26, -0.84]}>
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh
              geometry={nodes.Object_401.geometry}
              material={nodes.Object_401.material}
              skeleton={nodes.Object_401.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_403.geometry}
              material={nodes.Object_403.material}
              skeleton={nodes.Object_403.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_405.geometry}
              material={nodes.Object_405.material}
              skeleton={nodes.Object_405.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_407.geometry}
              material={nodes.Object_407.material}
              skeleton={nodes.Object_407.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_409.geometry}
              material={nodes.Object_409.material}
              skeleton={nodes.Object_409.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_411.geometry}
              material={nodes.Object_411.material}
              skeleton={nodes.Object_411.skeleton}
            />
          </group>
          <mesh geometry={nodes.Object_130.geometry} material={nodes.Object_130.material} />
          <group position={[-0.39, 1.41, -0.26]}>
            <mesh geometry={nodes.Object_80.geometry} material={nodes.Object_80.material} />
          </group>
          <group position={[0.02, 1.92, 0.07]}>
            <mesh geometry={nodes.Object_82.geometry} material={nodes.Object_82.material} />
          </group>
          <group position={[-0.06, 1.92, -0.03]}>
            <mesh geometry={nodes.Object_84.geometry} material={nodes.Object_84.material} />
          </group>
          <group position={[0.04, 1.92, -0.15]}>
            <mesh geometry={nodes.Object_86.geometry} material={nodes.Object_86.material} />
          </group>
          <group position={[-0.16, 1.75, 0.25]}>
            <mesh geometry={nodes.Object_88.geometry} material={nodes.Object_88.material} />
          </group>
          <group position={[0.16, 1.75, 0.25]}>
            <mesh geometry={nodes.Object_90.geometry} material={nodes.Object_90.material} />
          </group>
          <group position={[0.16, 1.75, -0.25]}>
            <mesh geometry={nodes.Object_92.geometry} material={nodes.Object_92.material} />
          </group>
          <group position={[-0.16, 1.75, -0.25]}>
            <mesh geometry={nodes.Object_94.geometry} material={nodes.Object_94.material} />
          </group>
          <group position={[-0.16, 1.8, -0.06]} rotation={[0, 0, Math.PI / 2]} scale={[0.9, 0.58, 0.9]}>
            <mesh geometry={nodes.Object_96.geometry} material={nodes.Object_96.material} />
          </group>
          <group position={[0.1, 1.41, 0.5]} rotation={[-0.05, 0, 0]}>
            <mesh geometry={nodes.Object_98.geometry} material={nodes.Object_98.material} />
          </group>
          <group position={[0.15, 1.41, 0.49]} rotation={[-0.05, 0, 0]}>
            <mesh geometry={nodes.Object_100.geometry} material={nodes.Object_100.material} />
          </group>
          <group position={[0.05, 1.41, 0.51]} rotation={[-0.05, 0, 0]}>
            <mesh geometry={nodes.Object_102.geometry} material={nodes.Object_102.material} />
          </group>
          <group position={[0.05, 1.56, 0.5]} rotation={[-0.05, 0, 0]}>
            <mesh geometry={nodes.Object_338.geometry} material={nodes.Object_338.material} />
          </group>
          <group position={[0.1, 1.56, 0.49]} rotation={[-0.05, 0, 0]}>
            <mesh geometry={nodes.Object_340.geometry} material={nodes.Object_340.material} />
          </group>
          <group position={[0.15, 1.56, 0.49]} rotation={[-0.05, 0, 0]}>
            <mesh geometry={nodes.Object_342.geometry} material={nodes.Object_342.material} />
          </group>
          <group position={[-0.46, 1.54, -0.09]}>
            <mesh geometry={nodes.Object_344.geometry} material={nodes.Object_344.material} />
          </group>
          <group position={[-0.39, 1.54, -0.26]}>
            <mesh geometry={nodes.Object_346.geometry} material={nodes.Object_346.material} />
          </group>
          <group position={[-0.16, 1.83, 0.25]}>
            <mesh geometry={nodes.Object_348.geometry} material={nodes.Object_348.material} />
          </group>
          <group position={[0.16, 1.83, 0.25]}>
            <mesh geometry={nodes.Object_350.geometry} material={nodes.Object_350.material} />
          </group>
          <group position={[0.16, 1.83, -0.25]}>
            <mesh geometry={nodes.Object_352.geometry} material={nodes.Object_352.material} />
          </group>
          <group position={[-0.16, 1.83, -0.25]}>
            <mesh geometry={nodes.Object_354.geometry} material={nodes.Object_354.material} />
          </group>
          <group position={[0.02, 1.92, 0.07]}>
            <mesh geometry={nodes.Object_370.geometry} material={nodes.Object_370.material} />
          </group>
          <group position={[-0.06, 1.92, -0.03]}>
            <mesh geometry={nodes.Object_372.geometry} material={nodes.Object_372.material} />
          </group>
          <group position={[0.04, 1.92, -0.15]}>
            <mesh geometry={nodes.Object_374.geometry} material={nodes.Object_374.material} />
          </group>
          <group position={[-0.16, 1.8, -0.06]} rotation={[0, 0, Math.PI / 2]} scale={[0.9, 0.58, 0.9]}>
            <mesh geometry={nodes.Object_386.geometry} material={nodes.Object_386.material} />
          </group>
          <group position={[-0.46, 1.41, -0.09]}>
            <mesh geometry={nodes.Object_104.geometry} material={nodes.Object_104.material} />
          </group>
          <group position={[-0.39, 1.41, -0.26]}>
            <mesh geometry={nodes.Object_106.geometry} material={nodes.Object_106.material} />
          </group>
          <group position={[-0.46, 1.41, -0.09]}>
            <mesh geometry={nodes.Object_78.geometry} material={nodes.Object_78.material} />
          </group>
          <group position={[0.44, 1.68, 0]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]}>
            <mesh geometry={nodes.Object_364.geometry} material={nodes.Object_364.material} />
          </group>
          <group position={[-0.31, 1.68, 0.31]}>
            <mesh geometry={nodes.Object_356.geometry} material={nodes.Object_356.material} />
          </group>
          <group position={[-0.31, 1.5, 0.31]}>
            <mesh geometry={nodes.Object_360.geometry} material={nodes.Object_360.material} />
          </group>
          <group position={[0.42, 1.49, 0]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]}>
            <mesh geometry={nodes.Object_362.geometry} material={nodes.Object_362.material} />
          </group>
          <group position={[0, 1.5, -0.43]} rotation={[Math.PI, -Math.PI / 4, Math.PI]}>
            <mesh geometry={nodes.Object_358.geometry} material={nodes.Object_358.material} />
          </group>
          <group position={[0, 1.68, -0.44]} rotation={[Math.PI, -Math.PI / 4, Math.PI]}>
            <mesh geometry={nodes.Object_366.geometry} material={nodes.Object_366.material} />
          </group>
          <mesh geometry={nodes.Object_368.geometry} material={nodes.Object_368.material} />
          <mesh geometry={nodes.Object_142.geometry} material={nodes.Object_142.material} />
          <group position={[0, 1.76, 0]}>
            <mesh geometry={nodes.Object_132.geometry} material={nodes.Object_132.material} />
          </group>
          <group position={[0, 1.84, 0]}>
            <mesh geometry={nodes.Object_144.geometry} material={nodes.Object_144.material} />
          </group>
          <group position={[0, 1.84, 0]}>
            <mesh geometry={nodes.Object_134.geometry} material={nodes.Object_134.material} />
          </group>
          <group position={[0, 1.82, 0]}>
            <mesh geometry={nodes.Object_136.geometry} material={nodes.Object_136.material} />
          </group>
          <group position={[0, 1.8, 0]}>
            <mesh geometry={nodes.Object_138.geometry} material={nodes.Object_138.material} />
          </group>
          <group position={[0, 1.78, 0]}>
            <mesh geometry={nodes.Object_140.geometry} material={nodes.Object_140.material} />
          </group>
          <group position={[0, 1.8, 0]}>
            <mesh geometry={nodes.Object_146.geometry} material={nodes.Object_146.material} />
          </group>
          <group position={[0, 1.82, 0]}>
            <mesh geometry={nodes.Object_148.geometry} material={nodes.Object_148.material} />
          </group>
          <group position={[0, 1.78, 0]}>
            <mesh geometry={nodes.Object_150.geometry} material={nodes.Object_150.material} />
          </group>
          <group position={[0, 1.76, 0]}>
            <mesh geometry={nodes.Object_152.geometry} material={nodes.Object_152.material} />
          </group>
          <group position={[0, 1.84, 0]}>
            <mesh geometry={nodes.Object_154.geometry} material={nodes.Object_154.material} />
          </group>
          <group position={[0, 1.8, 0]}>
            <mesh geometry={nodes.Object_158.geometry} material={nodes.Object_158.material} />
          </group>
          <group position={[0, 1.82, 0]}>
            <mesh geometry={nodes.Object_156.geometry} material={nodes.Object_156.material} />
          </group>
          <group position={[0, 1.78, 0]}>
            <mesh geometry={nodes.Object_160.geometry} material={nodes.Object_160.material} />
          </group>
          <group position={[0, 1.76, 0]}>
            <mesh geometry={nodes.Object_162.geometry} material={nodes.Object_162.material} />
          </group>
          <group position={[0, 1.84, 0]}>
            <mesh geometry={nodes.Object_164.geometry} material={nodes.Object_164.material} />
          </group>
          <group position={[0, 1.82, 0]}>
            <mesh geometry={nodes.Object_166.geometry} material={nodes.Object_166.material} />
          </group>
          <group position={[0, 1.8, 0]}>
            <mesh geometry={nodes.Object_168.geometry} material={nodes.Object_168.material} />
          </group>
          <group position={[0, 1.78, 0]}>
            <mesh geometry={nodes.Object_170.geometry} material={nodes.Object_170.material} />
          </group>
          <group position={[0, 1.76, 0]}>
            <mesh geometry={nodes.Object_172.geometry} material={nodes.Object_172.material} />
          </group>
          <mesh geometry={nodes.Object_128.geometry} material={nodes.Object_128.material} />
          <group position={[0, -0.6, 0]}>
            <mesh geometry={nodes.Object_274.geometry} material={nodes.Object_274.material} />
          </group>
          <group position={[0, -0.6, 0]}>
            <mesh geometry={nodes.Object_322.geometry} material={nodes.Object_322.material} />
          </group>
          <group position={[0, -0.6, 0]}>
            <mesh geometry={nodes.Object_262.geometry} material={nodes.Object_262.material} />
          </group>
          <group position={[-0.39, 1.62, -0.26]} rotation={[1.09, 0.38, 0.85]}>
            <mesh geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
          </group>
          <group position={[0.05, 1.6, 0.5]} rotation={[2.43, -0.03, -1.65]}>
            <mesh geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
          </group>
          <group position={[0.1, 1.6, 0.49]} rotation={[2.42, -0.1, -1.71]}>
            <mesh geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
          </group>
          <group position={[0.15, 1.6, 0.48]} rotation={[2.41, -0.16, -1.77]}>
            <mesh geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
          </group>
          <group position={[0, 1.59, -0.47]} rotation={[0, 0, Math.PI]} scale={0.19}>
            <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
          </group>
          <group position={[0, 1.56, -0.47]} rotation={[0, 0, Math.PI]} scale={0.19}>
            <mesh geometry={nodes.Object_16.geometry} material={nodes.Object_16.material} />
          </group>
          <group position={[0, 1.54, -0.47]} rotation={[0, 0, Math.PI]} scale={0.19}>
            <mesh geometry={nodes.Object_18.geometry} material={nodes.Object_18.material} />
          </group>
          <group position={[0, 1.52, -0.47]} rotation={[0, 0, Math.PI]} scale={0.19}>
            <mesh geometry={nodes.Object_20.geometry} material={nodes.Object_20.material} />
          </group>
          <group position={[0, 1.5, -0.47]} rotation={[0, 0, Math.PI]} scale={0.19}>
            <mesh geometry={nodes.Object_22.geometry} material={nodes.Object_22.material} />
          </group>
          <group position={[0, 1.48, -0.47]} rotation={[0, 0, Math.PI]} scale={0.19}>
            <mesh geometry={nodes.Object_24.geometry} material={nodes.Object_24.material} />
          </group>
          <group position={[0, 1.46, -0.47]} rotation={[0, 0, Math.PI]} scale={0.19}>
            <mesh geometry={nodes.Object_26.geometry} material={nodes.Object_26.material} />
          </group>
          <group position={[0, 1.44, -0.47]} rotation={[0, 0, Math.PI]} scale={0.19}>
            <mesh geometry={nodes.Object_28.geometry} material={nodes.Object_28.material} />
          </group>
          <group position={[0, 1.42, -0.47]} rotation={[0, 0, Math.PI]} scale={0.19}>
            <mesh geometry={nodes.Object_30.geometry} material={nodes.Object_30.material} />
          </group>
          <group position={[0.47, 1.59, 0]} rotation={[-Math.PI, -1.57, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_32.geometry} material={nodes.Object_32.material} />
          </group>
          <group position={[0.47, 1.56, 0]} rotation={[-Math.PI, -1.57, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_34.geometry} material={nodes.Object_34.material} />
          </group>
          <group position={[0.47, 1.54, 0]} rotation={[-Math.PI, -1.57, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_36.geometry} material={nodes.Object_36.material} />
          </group>
          <group position={[0.47, 1.52, 0]} rotation={[-Math.PI, -1.57, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_38.geometry} material={nodes.Object_38.material} />
          </group>
          <group position={[0.47, 1.5, 0]} rotation={[-Math.PI, -1.57, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_40.geometry} material={nodes.Object_40.material} />
          </group>
          <group position={[0.47, 1.48, 0]} rotation={[-Math.PI, -1.57, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_42.geometry} material={nodes.Object_42.material} />
          </group>
          <group position={[0.47, 1.46, 0]} rotation={[-Math.PI, -1.57, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_44.geometry} material={nodes.Object_44.material} />
          </group>
          <group position={[0.47, 1.44, 0]} rotation={[-Math.PI, -1.57, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_46.geometry} material={nodes.Object_46.material} />
          </group>
          <group position={[0.47, 1.42, 0]} rotation={[-Math.PI, -1.57, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_48.geometry} material={nodes.Object_48.material} />
          </group>
          <group position={[-0.34, 1.59, 0.33]} rotation={[-Math.PI, Math.PI / 4, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_50.geometry} material={nodes.Object_50.material} />
          </group>
          <group position={[-0.34, 1.56, 0.33]} rotation={[-Math.PI, Math.PI / 4, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_52.geometry} material={nodes.Object_52.material} />
          </group>
          <group position={[-0.34, 1.54, 0.33]} rotation={[-Math.PI, Math.PI / 4, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_54.geometry} material={nodes.Object_54.material} />
          </group>
          <group position={[-0.34, 1.52, 0.33]} rotation={[-Math.PI, Math.PI / 4, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_56.geometry} material={nodes.Object_56.material} />
          </group>
          <group position={[-0.34, 1.5, 0.33]} rotation={[-Math.PI, Math.PI / 4, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_58.geometry} material={nodes.Object_58.material} />
          </group>
          <group position={[-0.34, 1.48, 0.33]} rotation={[-Math.PI, Math.PI / 4, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_60.geometry} material={nodes.Object_60.material} />
          </group>
          <group position={[-0.34, 1.46, 0.33]} rotation={[-Math.PI, Math.PI / 4, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_62.geometry} material={nodes.Object_62.material} />
          </group>
          <group position={[-0.34, 1.44, 0.33]} rotation={[-Math.PI, Math.PI / 4, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_64.geometry} material={nodes.Object_64.material} />
          </group>
          <group position={[-0.34, 1.42, 0.33]} rotation={[-Math.PI, Math.PI / 4, 0]} scale={0.19}>
            <mesh geometry={nodes.Object_66.geometry} material={nodes.Object_66.material} />
          </group>
          <group position={[-0.46, 1.62, -0.09]} rotation={[1.42, 0.59, 0.16]}>
            <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
          </group>
          <group position={[0, -0.5, 0]}>
            <mesh geometry={nodes.Object_244.geometry} material={nodes.Object_244.material} />
          </group>
          <group position={[0.51, 1.41, -0.35]} rotation={[Math.PI / 2, 0, 1.01]}>
            <mesh geometry={nodes.Object_76.geometry} material={nodes.Object_76.material} />
          </group>
          <group position={[0.51, 1.41, 0.34]} rotation={[Math.PI / 2, 0, 2.2]}>
            <mesh geometry={nodes.Object_74.geometry} material={nodes.Object_74.material} />
          </group>
          <group position={[-0.6, 1.41, 0.12]} rotation={[Math.PI / 2, 0, -1.8]}>
            <mesh geometry={nodes.Object_70.geometry} material={nodes.Object_70.material} />
          </group>
          <group position={[-0.12, 1.41, 0.6]} rotation={[Math.PI / 2, 0, 0.21]}>
            <mesh geometry={nodes.Object_72.geometry} material={nodes.Object_72.material} />
          </group>
          <group position={[0.7, 1.41, -0.47]} rotation={[-0.79, -0.06, -0.85]}>
            <mesh geometry={nodes.Object_108.geometry} material={nodes.Object_108.material} />
          </group>
          <group position={[-0.47, 1.41, -0.7]} rotation={[-Math.PI / 2, Math.PI / 4, Math.PI / 4]}>
            <mesh geometry={nodes.Object_110.geometry} material={nodes.Object_110.material} />
          </group>
          <group position={[-0.82, 1.41, 0.16]} rotation={[-2.33, 0.24, 2.1]}>
            <mesh geometry={nodes.Object_112.geometry} material={nodes.Object_112.material} />
          </group>
          <group position={[-0.16, 1.41, 0.82]} rotation={[-2.19, -Math.PI / 6, 2.97]}>
            <mesh geometry={nodes.Object_114.geometry} material={nodes.Object_114.material} />
          </group>
          <group position={[0.7, 1.41, 0.47]} rotation={[-1.24, -0.73, -1.88]}>
            <mesh geometry={nodes.Object_116.geometry} material={nodes.Object_116.material} />
          </group>
          <group position={[0.1, -0.79, 0.51]} rotation={[Math.PI / 2, 0, 2.93]}>
            <mesh geometry={nodes.Object_246.geometry} material={nodes.Object_246.material} />
          </group>
          <group position={[0.24, 1.54, 0.45]} rotation={[-0.14, -0.96, 1.54]}>
            <mesh geometry={nodes.Object_178.geometry} material={nodes.Object_178.material} />
          </group>
          <group position={[0.32, 1.54, 0.39]} rotation={[-1.64, -0.05, 0.61]}>
            <mesh geometry={nodes.Object_174.geometry} material={nodes.Object_174.material} />
          </group>
          <group position={[0.28, 1.54, 0.42]} rotation={[2.57, 0.91, 1.95]}>
            <mesh geometry={nodes.Object_176.geometry} material={nodes.Object_176.material} />
          </group>
          <group position={[0.43, -0.79, 0.29]} rotation={[Math.PI / 2, 0, 2.15]}>
            <mesh geometry={nodes.Object_248.geometry} material={nodes.Object_248.material} />
          </group>
          <group position={[0.51, -0.79, -0.1]} rotation={[Math.PI / 2, 0, 1.36]}>
            <mesh geometry={nodes.Object_250.geometry} material={nodes.Object_250.material} />
          </group>
          <group position={[0.29, -0.79, -0.43]} rotation={[Math.PI / 2, 0, 0.58]}>
            <mesh geometry={nodes.Object_252.geometry} material={nodes.Object_252.material} />
          </group>
          <group position={[-0.1, -0.79, -0.51]} rotation={[Math.PI / 2, 0, -0.21]}>
            <mesh geometry={nodes.Object_254.geometry} material={nodes.Object_254.material} />
          </group>
          <group position={[-0.43, -0.79, -0.29]} rotation={[Math.PI / 2, 0, -0.99]}>
            <mesh geometry={nodes.Object_256.geometry} material={nodes.Object_256.material} />
          </group>
          <group position={[-0.16, 1.41, 0.82]} rotation={[-2.19, -Math.PI / 6, 2.97]}>
            <mesh geometry={nodes.Object_118.geometry} material={nodes.Object_118.material} />
          </group>
          <group position={[-0.51, -0.79, 0.1]} rotation={[Math.PI / 2, 0, -1.78]}>
            <mesh geometry={nodes.Object_258.geometry} material={nodes.Object_258.material} />
          </group>
          <group position={[0.7, 1.41, 0.47]} rotation={[-1.24, -0.73, -1.88]}>
            <mesh geometry={nodes.Object_120.geometry} material={nodes.Object_120.material} />
          </group>
          <group position={[0.7, 1.41, -0.47]} rotation={[-0.79, -0.06, -0.85]}>
            <mesh geometry={nodes.Object_122.geometry} material={nodes.Object_122.material} />
          </group>
          <group position={[-0.47, 1.41, -0.7]} rotation={[-Math.PI / 2, Math.PI / 4, Math.PI / 4]}>
            <mesh geometry={nodes.Object_124.geometry} material={nodes.Object_124.material} />
          </group>
          <group position={[-0.29, -0.79, 0.43]} rotation={[Math.PI / 2, 0, -2.57]}>
            <mesh geometry={nodes.Object_260.geometry} material={nodes.Object_260.material} />
          </group>
          <group position={[-0.82, 1.41, 0.16]} rotation={[-2.33, 0.24, 2.1]}>
            <mesh geometry={nodes.Object_126.geometry} material={nodes.Object_126.material} />
          </group>
          <group position={[-0.47, 1.41, -0.7]} rotation={[-Math.PI / 2, Math.PI / 4, Math.PI / 4]}>
            <mesh geometry={nodes.Object_376.geometry} material={nodes.Object_376.material} />
          </group>
          <group position={[-0.82, 1.41, 0.16]} rotation={[-2.33, 0.24, 2.1]}>
            <mesh geometry={nodes.Object_378.geometry} material={nodes.Object_378.material} />
          </group>
          <group position={[-0.16, 1.41, 0.82]} rotation={[-2.19, -Math.PI / 6, 2.97]}>
            <mesh geometry={nodes.Object_380.geometry} material={nodes.Object_380.material} />
          </group>
          <group position={[0.7, 1.41, 0.47]} rotation={[-1.24, -0.73, -1.88]}>
            <mesh geometry={nodes.Object_382.geometry} material={nodes.Object_382.material} />
          </group>
          <group position={[0.7, 1.41, -0.47]} rotation={[-0.79, -0.06, -0.85]}>
            <mesh geometry={nodes.Object_384.geometry} material={nodes.Object_384.material} />
          </group>
          <group position={[0.51, 1.41, 0.34]} rotation={[Math.PI / 2, 0, 2.2]}>
            <mesh geometry={nodes.Object_284.geometry} material={nodes.Object_284.material} />
          </group>
          <group position={[0.51, 1.41, -0.35]} rotation={[Math.PI / 2, 0, 1.01]}>
            <mesh geometry={nodes.Object_292.geometry} material={nodes.Object_292.material} />
          </group>
          <group position={[-0.34, 1.45, -0.52]} rotation={[Math.PI / 2, 0, -0.59]}>
            <mesh geometry={nodes.Object_286.geometry} material={nodes.Object_286.material} />
          </group>
          <group position={[-0.6, 1.41, 0.12]} rotation={[Math.PI / 2, 0, -1.8]}>
            <mesh geometry={nodes.Object_288.geometry} material={nodes.Object_288.material} />
          </group>
          <group position={[-0.12, 1.41, 0.6]} rotation={[Math.PI / 2, 0, 0.21]}>
            <mesh geometry={nodes.Object_290.geometry} material={nodes.Object_290.material} />
          </group>
          <group position={[0.51, 1.41, -0.35]} rotation={[Math.PI / 2, 0, 1.01]}>
            <mesh geometry={nodes.Object_388.geometry} material={nodes.Object_388.material} />
          </group>
          <group position={[0.51, 1.41, 0.34]} rotation={[Math.PI / 2, 0, 2.2]}>
            <mesh geometry={nodes.Object_390.geometry} material={nodes.Object_390.material} />
          </group>
          <group position={[-0.12, 1.41, 0.6]} rotation={[Math.PI / 2, 0, 0.21]}>
            <mesh geometry={nodes.Object_392.geometry} material={nodes.Object_392.material} />
          </group>
          <group position={[-0.6, 1.41, 0.12]} rotation={[Math.PI / 2, 0, -1.8]}>
            <mesh geometry={nodes.Object_394.geometry} material={nodes.Object_394.material} />
          </group>
          <group position={[-0.34, 1.45, -0.52]} rotation={[Math.PI / 2, 0, -0.59]}>
            <mesh geometry={nodes.Object_396.geometry} material={nodes.Object_396.material} />
          </group>
          <group position={[-0.34, 1.45, -0.52]} rotation={[Math.PI / 2, 0, -0.59]}>
            <mesh geometry={nodes.Object_68.geometry} material={nodes.Object_68.material} />
          </group>
          <group position={[-0.74, 0.59, 1.23]} rotation={[-3.12, -0.98, -1.05]}>
            <mesh geometry={nodes.Object_190.geometry} material={nodes.Object_190.material} />
          </group>
          <group position={[-0.94, 0.43, 1.2]} rotation={[-1.79, 0.57, -0.61]}>
            <mesh geometry={nodes.Object_186.geometry} material={nodes.Object_186.material} />
          </group>
          <group position={[-0.8, 0.43, 1.29]} rotation={[-2, 0.3, -0.61]}>
            <mesh geometry={nodes.Object_192.geometry} material={nodes.Object_192.material} />
          </group>
          <group position={[-0.99, 0.28, 1.26]} rotation={[1.19, -0.35, -2.6]}>
            <mesh geometry={nodes.Object_188.geometry} material={nodes.Object_188.material} />
          </group>
          <group position={[-0.85, 0.28, 1.36]} rotation={[1.19, -0.35, -2.6]}>
            <mesh geometry={nodes.Object_194.geometry} material={nodes.Object_194.material} />
          </group>
          <group position={[-0.89, 0.59, 1.13]} rotation={[-3.12, -0.98, -1.05]}>
            <mesh geometry={nodes.Object_184.geometry} material={nodes.Object_184.material} />
          </group>
          <group position={[0.28, 1.5, 0.42]}>
            <mesh geometry={nodes.Object_180.geometry} material={nodes.Object_180.material} />
          </group>
          <group position={[0.29, 0.41, 1.49]} rotation={[-2.01, 0.02, -2.95]} scale={[0.8, 1, 0.8]}>
            <mesh geometry={nodes.Object_208.geometry} material={nodes.Object_208.material} />
          </group>
          <group position={[1.51, 0.42, -0.3]} rotation={[-1.57, -0.45, -1.39]}>
            <group scale={[0.25, 0.25, 0.25]}>
              <mesh geometry={nodes.Object_198.geometry} material={nodes.Object_198.material} />
            </group>
            <group rotation={[-Math.PI, 0, -Math.PI]} scale={[0.25, 0.25, 0.25]}>
              <mesh geometry={nodes.Object_200.geometry} material={nodes.Object_200.material} />
            </group>
            <mesh geometry={nodes.Object_196.geometry} material={nodes.Object_196.material} />
          </group>
          <group position={[0.66, 0.42, 1.39]} rotation={[-2.16, 1.39, 1.69]} scale={[1.5, 1.5, 1.5]}>
            <mesh geometry={nodes.Object_218.geometry} material={nodes.Object_218.material} />
          </group>
          <group position={[0.84, 0.42, 1.28]} rotation={[-2.32, 1.32, 1.88]} scale={[1.5, 1.5, 1.5]}>
            <mesh geometry={nodes.Object_220.geometry} material={nodes.Object_220.material} />
          </group>
          <group position={[1, 0.42, 1.16]} rotation={[-2.4, 1.24, 1.99]} scale={[1.5, 1.5, 1.5]}>
            <mesh geometry={nodes.Object_222.geometry} material={nodes.Object_222.material} />
          </group>
          <group position={[1.45, 0.33, -0.67]} rotation={[-2.93, -0.04, 2.69]}>
            <mesh geometry={nodes.Object_224.geometry} material={nodes.Object_224.material} />
          </group>
          <group position={[1.31, 0.48, -0.76]} rotation={[-2.93, -0.12, 2.7]} scale={[1.3, 1.3, 1.3]}>
            <mesh geometry={nodes.Object_226.geometry} material={nodes.Object_226.material} />
          </group>
          <group position={[-0.68, 0.32, 1.45]} rotation={[-0.28, 0.72, -0.28]}>
            <mesh geometry={nodes.Object_296.geometry} material={nodes.Object_296.material} />
          </group>
          <group position={[0.66, 0.42, 1.39]} rotation={[-2.16, 1.39, 1.69]} scale={[1.5, 1.5, 1.5]}>
            <mesh geometry={nodes.Object_298.geometry} material={nodes.Object_298.material} />
          </group>
          <group position={[0.84, 0.42, 1.28]} rotation={[-2.32, 1.32, 1.88]} scale={[1.5, 1.5, 1.5]}>
            <mesh geometry={nodes.Object_300.geometry} material={nodes.Object_300.material} />
          </group>
          <group position={[1, 0.42, 1.16]} rotation={[-2.4, 1.24, 1.99]} scale={[1.5, 1.5, 1.5]}>
            <mesh geometry={nodes.Object_302.geometry} material={nodes.Object_302.material} />
          </group>
          <group position={[1.45, 0.33, -0.67]} rotation={[-2.93, -0.04, 2.69]}>
            <mesh geometry={nodes.Object_304.geometry} material={nodes.Object_304.material} />
          </group>
          <group position={[1.31, 0.48, -0.76]} rotation={[-2.93, -0.12, 2.7]} scale={[1.3, 1.3, 1.3]}>
            <mesh geometry={nodes.Object_306.geometry} material={nodes.Object_306.material} />
          </group>
          <group position={[-0.68, 0.32, 1.45]} rotation={[-0.28, 0.72, -0.28]}>
            <mesh geometry={nodes.Object_308.geometry} material={nodes.Object_308.material} />
          </group>
          <group position={[0.66, 0.42, 1.39]} rotation={[-2.16, 1.39, 1.69]} scale={[1.5, 1.5, 1.5]}>
            <mesh geometry={nodes.Object_310.geometry} material={nodes.Object_310.material} />
          </group>
          <group position={[0.84, 0.42, 1.28]} rotation={[-2.32, 1.32, 1.88]} scale={[1.5, 1.5, 1.5]}>
            <mesh geometry={nodes.Object_312.geometry} material={nodes.Object_312.material} />
          </group>
          <group position={[1, 0.42, 1.16]} rotation={[-2.4, 1.24, 1.99]} scale={[1.5, 1.5, 1.5]}>
            <mesh geometry={nodes.Object_314.geometry} material={nodes.Object_314.material} />
          </group>
          <group position={[1.45, 0.33, -0.67]} rotation={[-2.93, -0.04, 2.69]}>
            <mesh geometry={nodes.Object_316.geometry} material={nodes.Object_316.material} />
          </group>
          <group position={[1.31, 0.48, -0.76]} rotation={[-2.93, -0.12, 2.7]} scale={[1.3, 1.3, 1.3]}>
            <mesh geometry={nodes.Object_318.geometry} material={nodes.Object_318.material} />
          </group>
          <group position={[-0.68, 0.32, 1.45]} rotation={[-0.28, 0.72, -0.28]}>
            <mesh geometry={nodes.Object_216.geometry} material={nodes.Object_216.material} />
          </group>
          <group position={[-0.3, 0.41, 1.49]} rotation={[-2, 0.08, 2.96]}>
            <group rotation={[Math.PI, 0, Math.PI]} scale={0.25}>
              <mesh geometry={nodes.Object_206.geometry} material={nodes.Object_206.material} />
            </group>
            <group scale={[0.25, 0.25, 0.25]}>
              <mesh geometry={nodes.Object_204.geometry} material={nodes.Object_204.material} />
            </group>
            <mesh geometry={nodes.Object_202.geometry} material={nodes.Object_202.material} />
          </group>
          <group position={[0.29, 0.42, 1.5]} rotation={[-2.41, 1.11, -2.7]} scale={[0.2, 0.2, 0.2]}>
            <mesh geometry={nodes.Object_266.geometry} material={nodes.Object_266.material} />
          </group>
          <group position={[0.29, 0.41, 1.49]} rotation={[0.73, -1.11, -0.45]} scale={[0.2, 0.2, 0.2]}>
            <mesh geometry={nodes.Object_276.geometry} material={nodes.Object_276.material} />
          </group>
          <group position={[-0.52, -0.69, 0.78]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]}>
            <mesh geometry={nodes.Object_228.geometry} material={nodes.Object_228.material} />
          </group>
          <mesh geometry={nodes.Object_320.geometry} material={nodes.Object_320.material} />
          <group position={[0.78, -0.69, 0.52]} rotation={[Math.PI, -Math.PI / 4, Math.PI]}>
            <mesh geometry={nodes.Object_230.geometry} material={nodes.Object_230.material} />
          </group>
          <group position={[0.92, -0.69, -0.18]} rotation={[0, -1.57, 0]}>
            <mesh geometry={nodes.Object_232.geometry} material={nodes.Object_232.material} />
          </group>
          <group position={[0.52, -0.69, -0.78]} rotation={[0, -Math.PI / 4, 0]}>
            <mesh geometry={nodes.Object_234.geometry} material={nodes.Object_234.material} />
          </group>
          <group position={[-0.18, -0.69, -0.92]}>
            <mesh geometry={nodes.Object_236.geometry} material={nodes.Object_236.material} />
          </group>
          <group position={[-0.78, -0.69, -0.52]} rotation={[0, Math.PI / 4, 0]}>
            <mesh geometry={nodes.Object_238.geometry} material={nodes.Object_238.material} />
          </group>
          <group position={[-0.92, -0.69, 0.18]} rotation={[0, 1.57, 0]}>
            <mesh geometry={nodes.Object_240.geometry} material={nodes.Object_240.material} />
          </group>
          <group position={[0.18, -0.69, 0.92]} rotation={[Math.PI, 0, Math.PI]}>
            <mesh geometry={nodes.Object_242.geometry} material={nodes.Object_242.material} />
          </group>
          <mesh geometry={nodes.Object_182.geometry} material={nodes.Object_182.material} />
          <group position={[0, 0.9, 0]}>
            <mesh geometry={nodes.Object_264.geometry} material={nodes.Object_264.material} />
          </group>
          <group position={[0, -0.85, 0]} scale={0.9}>
            <mesh geometry={nodes.Object_332.geometry} material={nodes.Object_332.material} />
          </group>
          <group position={[0, -0.85, 0]} scale={0.72}>
            <mesh geometry={nodes.Object_334.geometry} material={nodes.Object_334.material} />
          </group>
          <group position={[0, -0.85, 0]} scale={0.58}>
            <mesh geometry={nodes.Object_336.geometry} material={nodes.Object_336.material} />
          </group>
          <group position={[0, -0.85, 0]}>
            <mesh geometry={nodes.Object_330.geometry} material={nodes.Object_330.material} />
          </group>
          <group position={[-0.67, 0.63, -0.67]}>
            <mesh geometry={nodes.Object_328.geometry} material={nodes.Object_328.material} />
          </group>
          <group position={[-0.67, 0.63, -0.67]}>
            <mesh geometry={nodes.Object_210.geometry} material={nodes.Object_210.material} />
          </group>
          <group position={[-0.72, 0.42, -0.72]}>
            <mesh geometry={nodes.Object_212.geometry} material={nodes.Object_212.material} />
          </group>
          <group position={[-0.77, 0.21, -0.77]}>
            <mesh geometry={nodes.Object_214.geometry} material={nodes.Object_214.material} />
          </group>
          <group position={[-0.72, 0.42, -0.72]}>
            <mesh geometry={nodes.Object_326.geometry} material={nodes.Object_326.material} />
          </group>
          <group position={[-0.77, 0.21, -0.77]}>
            <mesh geometry={nodes.Object_324.geometry} material={nodes.Object_324.material} />
          </group>
          <group position={[-0.88, 0.22, -0.88]}>
            <mesh geometry={nodes.Object_268.geometry} material={nodes.Object_268.material} />
          </group>
          <group position={[-0.82, 0.42, -0.82]}>
            <mesh geometry={nodes.Object_270.geometry} material={nodes.Object_270.material} />
          </group>
          <group position={[-0.76, 0.63, -0.76]}>
            <mesh geometry={nodes.Object_278.geometry} material={nodes.Object_278.material} />
          </group>
          <group position={[-0.82, 0.42, -0.82]}>
            <mesh geometry={nodes.Object_280.geometry} material={nodes.Object_280.material} />
          </group>
          <group position={[-0.88, 0.22, -0.88]}>
            <mesh geometry={nodes.Object_282.geometry} material={nodes.Object_282.material} />
          </group>
          <group position={[-0.76, 0.63, -0.76]}>
            <mesh geometry={nodes.Object_272.geometry} material={nodes.Object_272.material} />
          </group>
          <group position={[0, 4.06, 0]} scale={[0.3, 0.06, 0.3]}>
            <mesh geometry={nodes.Object_294.geometry} material={nodes.Object_294.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Brainz.gltf')
